[firebase]
apiKey = "AIzaSyBftrXBEOxgUGKKg1Om1FtXA4oXhejtPcI"
authDomain = "corn-maturity-ai.firebaseapp.com"
projectId = "corn-maturity-ai"
storageBucket = "corn-maturity-ai.firebasestorage.app"
messagingSenderId = "128451318589"
appId = "1:128451318589:web:41a5f1a65924583394ab54"
measurementId = "G-KSH364WNN0"
databaseURL = "https://corn-maturity-ai-default-rtdb.asia-southeast1.firebasedatabase.app"
